apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: bespin-revproxy
  name: bespin-revproxy
spec:
  host: ""
  port:
    targetPort: 8080-tcp
  to:
    kind: ""
    name: bespin-revproxy
    weight: null
  tls:
    termination: edge
status:
  ingress: []
