apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: dukegcb/bespin-api:1.2.2-apache-openshift
      from:
        kind: DockerImage
        name: dukegcb/bespin-api:1.2.2-apache-openshift
      generation: null
      importPolicy: {}
      name: 1.2.2-apache
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    replicas: 1
    selector:
      app: bespin-api
      deploymentconfig: bespin-api
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: bespin-api
          deploymentconfig: bespin-api
      spec:
        containers:
        - image: dukegcb/bespin-api:1.2.2-apache-openshift
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-password
            - name: BESPIN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-host
          volumeMounts:
          - name: bespin-web-certs-volume
            mountPath: /bespin-web-certs/
            readOnly: true
          name: bespin-api
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /srv/ui
            name: bespin-api-volume-1
          - mountPath: /bespin-web-certs/
            name: bespin-web-certs-volume
        volumes:
        - emptyDir: {}
          name: bespin-api-volume-1
        - name: bespin-web-certs-volume
          secret:
            secretName: bespin-web-cert
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - bespin-api
        from:
          kind: ImageStreamTag
          name: bespin-api:1.2.2-apache-openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: bespin-api
      deploymentconfig: bespin-api
  status:
    loadBalancer: {}
kind: List
metadata: {}
