apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    host: "bespin-web.192.168.64.5.nip.io"
    path: /api/
    port:
      targetPort: 8080-tcp
    to:
      kind: ""
      name: bespin-api
      weight: null
  status:
    ingress: []
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api-staticfiles
  spec:
    host: "bespin-web.192.168.64.5.nip.io"
    path: /static/
    port:
      targetPort: 8080-tcp
    to:
      kind: ""
      name: bespin-api
      weight: null
  status:
    ingress: []
