apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: dukegcb/bespin-api
      from:
        kind: DockerImage
        name: dukegcb/bespin-api:1.2.2-apache
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    replicas: 1
    selector:
      app: bespin-api
      deploymentconfig: bespin-api
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: bespin-api
          deploymentconfig: bespin-api
      spec:
        containers:
        - image: dukegcb/bespin-api:1.2.2-apache
          env:
            - name: BESPIN_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-name
            - name: BESPIN_DB_USER
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-user
            - name: BESPIN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-password
            - name: BESPIN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-host
          name: bespin-api
          ports:
          - containerPort: 8000
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - bespin-api
        from:
          kind: ImageStreamTag
          name: bespin-api:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: bespin-api
      deploymentconfig: bespin-api
  status:
    loadBalancer: {}
kind: List
metadata: {}
