apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: bespin-api:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: openshift
        uri: https://github.com/dleehr/bespin-api
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:2.7
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 7RHLwRdifBI7QKlbjEBq
      type: GitHub
    - generic:
        secret: TB7TnoC5mAImvOP6ZELa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    replicas: 1
    selector:
      app: bespin-api
      deploymentconfig: bespin-api
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: bespin-api
          deploymentconfig: bespin-api
      spec:
        containers:
        - image: bespin-api:latest
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-password
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-host
            - name: DJANGO_SETTINGS_MODULE
              value: bespin.settings_prod
            - name: BESPIN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bespin-api-config
                  key: bespin-secret-key
          name: bespin-api
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - bespin-api
        from:
          kind: ImageStreamTag
          name: bespin-api:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-api
    name: bespin-api
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: bespin-api
      deploymentconfig: bespin-api
  status:
    loadBalancer: {}
kind: List
metadata: {}
