apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql-95-centos7
    name: postgresql-95-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos/postgresql-95-centos7
      from:
        kind: DockerImage
        name: centos/postgresql-95-centos7
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql-95-centos7
    name: postgresql-95-centos7
  spec:
    replicas: 1
    selector:
      app: postgresql-95-centos7
      deploymentconfig: postgresql-95-centos7
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: postgresql-95-centos7
          deploymentconfig: postgresql-95-centos7
      spec:
        containers:
        - image: centos/postgresql-95-centos7
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bespin-db-config
                  key: db-password
          name: postgresql-95-centos7
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-95-centos7-volume-1
        volumes:
        - emptyDir: {}
          name: postgresql-95-centos7-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql-95-centos7
        from:
          kind: ImageStreamTag
          name: postgresql-95-centos7:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql-95-centos7
    name: db
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgresql-95-centos7
      deploymentconfig: postgresql-95-centos7
  status:
    loadBalancer: {}
kind: List
metadata: {}
