apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-revproxy
    name: httpd-24-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos/httpd-24-centos7
      from:
        kind: DockerImage
        name: centos/httpd-24-centos7
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-revproxy
    name: bespin-revproxy
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-revproxy
    name: bespin-revproxy
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: bespin-revproxy:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/openshift/httpd-ex
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: httpd-24-centos7:latest
      type: Source
    triggers:
    - github:
        secret: RItxVDK4GuMrVVauHv72
      type: GitHub
    - generic:
        secret: ORY-aAvF8iTiO35hofG5
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-revproxy
    name: bespin-revproxy
  spec:
    replicas: 1
    selector:
      app: bespin-revproxy
      deploymentconfig: bespin-revproxy
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: bespin-revproxy
          deploymentconfig: bespin-revproxy
      spec:
        containers:
        - image: bespin-revproxy:latest
          name: bespin-revproxy
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - bespin-revproxy
        from:
          kind: ImageStreamTag
          name: bespin-revproxy:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: bespin-revproxy
    name: bespin-revproxy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: bespin-revproxy
      deploymentconfig: bespin-revproxy
  status:
    loadBalancer: {}
kind: List
metadata: {}
