apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: httpd-ex
  name: httpd-ex
spec:
  host: "bespin-web.192.168.64.5.nip.io"
  path: /
  port:
    targetPort: 8080-tcp
  to:
    kind: ""
    name: httpd-ex
    weight: null
status:
  ingress: []
